pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        // 国内镜像加速
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://mirrors.tuna.tsinghua.edu.cn/google' }
        maven { url 'https://mirrors.tuna.tsinghua.edu.cn/maven-central' }
        maven { url 'https://mirrors.tuna.tsinghua.edu.cn/jcenter' }
    }
}

dependencyResolutionManagement {
    // 关键：统一仓库声明，禁止在build.gradle中额外定义repositories
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // 必须添加，用于拉取 Xposed API 依赖
        // 国内镜像加速
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://mirrors.tuna.tsinghua.edu.cn/google' }
        maven { url 'https://mirrors.tuna.tsinghua.edu.cn/maven-central' }
        maven { url 'https://mirrors.tuna.tsinghua.edu.cn/jcenter' }
    }
}

// 项目名称，保持和你仓库一致
rootProject.name = "ActivityMonitor"
include ':app'
